# Protocoale de comunicatii:
# Makefile

CFLAGS = -Wall -g

all: server subscriber

# Compileaza server.c
server: server.c

# Compileaza subscriber.c
subscriber: subscriber.c

clean:
	rm -f server subscriber
